# Makefile for Android Terminal IDE.

DIRS=.
OBJECTS=main.o dcpu.o dcpu_ops.o
SOURCES=*.c
HEADS=*.h
TARGET=dcpu_emu

CC=terminal-gcc

.PHONY: all
all: ${TARGET}

${TARGET}: ${OBJECTS}
	${CC} -o $@ ${OBJECTS}

${OBJECTS}: ${HEADS}

.PHONY: clean
clean: cleanobj cleantgt

.PHONY: cleanobj
cleanobj:
	rm -rf ${OBJECTS}

.PHONY: cleantgt
cleantgt:
	rm -rf ${TARGET}
