# Makefile for Android Terminal IDE.

DIRS=.
OBJECTS=*.o
SOURCES=*.c
TARGET=dcpu_emu

CC=terminal-gcc

.PHONY: all
all: ${TARGET}

${TARGET}: ${SOURCES}
	${CC} -o ${TARGET} ${SOURCES}

.PHONY: clean
clean:
	-rm ${TARGET}
